prefix               = "barbot-test"
bot_username         = "CityFursBarTESTBot"
telegram_bot_token   = ""
main_chat_id         = ""
bar_spreadsheet      = ""
selenium_server_url  = ""

aws_region           = "us-west-2"
timezone             = "America/Los_Angeles"
first_reminder_cron  = "0/10 * ? * * *"
create_poll_cron     = "3/10 * ? * * *"
last_call_cron       = "5/10 * ? * * *"
close_poll_cron      = "8/10 * ? * * *"
