prefix               = "barbot"
bot_username         = "CityFursBarBot"
telegram_bot_token   = ""
main_chat_id         = ""
bar_spreadsheet      = ""

aws_region           = "us-west-2"
timezone             = "America/Los_Angeles"
first_reminder_cron  = "0 10 ? * MON *"
create_poll_cron     = "0 20 ? * MON *"
last_call_cron       = "0 10 ? * TUE *"
close_poll_cron      = "0 20 ? * TUE *"